[package]
name = "rsky-common-web"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
libipld = { version = "0.16.0", features = ["serde-codec"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"