name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

env:
  PDS_EMAIL_FROM_ADDRESS: "noreply@blacksky.app"
  PDS_EMAIL_FROM_NAME: "noreply"
  PDS_MODERATION_EMAIL_FROM_NAME: "noreply"
  PDS_MODERATION_EMAIL_FROM_ADDRESS: "noreply@blacksky.app"
  PDS_HOSTNAME: "rsky.com"
  PDS_SERVICE_DID: "did:web:localho.st"
  PDS_SERVICE_HANDLE_DOMAINS: ".rsky.com"
  PDS_ADMIN_PASS: 3ed1c7b568d3328c44430add531a099f
  PDS_JWT_KEY_K256_PRIVATE_KEY_HEX: 9d5907143471e8f0e8df0f8b9512a8c5377878ee767f18fcf961055ecfc071cd
  #  PDS_ADMIN_PASS: ${{ secrets.PDS_ADMIN_PASS }}
  #  PDS_JWT_KEY_K256_PRIVATE_KEY_HEX: ${{ secrets.PDS_JWT_KEY_K256_PRIVATE_KEY_HEX }}
  PDS_MAILGUN_API_KEY: ${{ secrets.PDS_MAILGUN_API_KEY }}
  PDS_MAILGUN_DOMAIN: ${{ secrets.PDS_MAILGUN_DOMAIN }}
  #PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ${{ secrets.PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX }}
  #PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX: ${{ secrets.PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX }}
  PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: fb478b39dd2ddf84bef135dd60f90381903eefadbb9df4b18a2b9b174ae72582
  PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX: 71cfcf4882a6cff494c3d0affadd3858eb3a5838e7b5e15170e696a590a4fa01

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show disk usage (before cleanup)
        run: df -h

      - name: Clean up large directories
        run: |
          sudo rm -rf /usr/local/share/boost \
                      /usr/share/dotnet \
                      /usr/local/lib/android \
                      /opt/ghc

      - name: Show disk usage (after cleanup)
        run: df -h

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo build
        run: |
          # Optional: You can do a `cargo clean` here if you want a fresh build each time:
          # cargo clean
          cargo build --release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test

  # clippy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Rust Cache
  #     uses: Swatinem/rust-cache@v2
  #   - name: Run Clippy
  #     run: cargo clippy -- -D warnings

  formatting:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt -- --check